### ISSUE TITLE
Just wanted to contact you for Dell vostro 3578 efi

### ISSUE THREAD

**Issue by kasai2210** [phucdc/linux#1]
Hii, this is not exactly an issue, can I get your discord or something, because I see that you have starred this repository - [https://github.com/ABCDFAS/hackintosh-vostro-3578-opencore-EFI](url) and I have some issues running this. Let me know if you have successfully booted this up or not?

If yes, then please share your contact or maybe link your EFI so that I can also try it out.

Waiting for your response!!

**Comment by phucdc** [comment]
not actually works on my machine, i given up

**Comment by kasai2210** [comment]
Hey, I have got it to work on my pc, tell me if you need my EFI.

**Comment by phucdc** [comment]
thanks, but i don't need anymore, good job bro
